local path = minetest.get_modpath("summer")
dofile(path.."/salvag.lua")
dofile(path.."/ombrellone.lua")
dofile(path.."/sdraia.lua")
-- dofile(path.."/porta.lua") -- dočasně vypnuto
dofile(path.."/ombrellone_new.lua")
dofile(path.."/materassino.lua")
dofile(path.."/asciugamano.lua")
dofile(path.."/barche.lua")
dofile(path.."/granite.lua")
dofile(path.."/canoa.lua")
dofile(path.."/craft.lua")
-- dofile(path.."/vetro.lua") -- není špatné, možná někdy zapnout
dofile(path.."/sabbia.lua")
dofile(path.."/mattone.lua")
dofile(path.."/pallone.lua")
