--[[
    signs_road mod for Minetest - Various road signs with text displayed
    on.
    (c) Pierre-Yves Rollo

    This file is part of signs_road.

    signs_road is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    signs_road is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with signs_road.  If not, see <http://www.gnu.org/licenses/>.
--]]

local S = signs_road.intllib

local prefix5 = "[combine:32x32:-16,-16=ch_core_5.png^"

local models = {
	blue_street_sign = {
		depth = 1/16,
		width = 14/16,
		height = 12/16,
		entity_fields = {
			size = { x = 14/16, y = 10/16 },
			maxlines = 3,
			color = "#fff",
		},
		node_fields = {
			description = S("Blue street sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_blue_street.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_blue_street.png",
		},
		allow_on_pole = true,
	},
	large_street_sign = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#000",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large banner"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_large_white.png" },
			use_texture_alpha = "opaque",
			inventory_image = prefix5.."signs_road_white.png",
		},
	},
	blue_large_street_sign = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#fff",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large blue banner"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_large_white.png^[multiply:#0040C0" },
			use_texture_alpha = "opaque",
			inventory_image = prefix5.."(signs_road_white.png^[multiply:#0040C0)",
		},
	},
	green_large_street_sign = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#fff",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large green banner"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_large_white.png^[multiply:#008040" },
			use_texture_alpha = "opaque",
			inventory_image = prefix5.."(signs_road_white.png^[multiply:#008040)",
		},
	},
	red_large_street_sign = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#fff",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large red banner"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_large_white.png^[multiply:#ff0000" },
			use_texture_alpha = "opaque",
			inventory_image = prefix5.."(signs_road_white.png^[multiply:#ff0000)",
		},
	},
	black_large_street_sign = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#fff",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large black banner"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_large_white.png^[multiply:#000000" },
			use_texture_alpha = "opaque",
			inventory_image = prefix5.."(signs_road_white.png^[multiply:#000000)",
		},
	},
	yellow_large_street_sign = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#000",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large yellow banner"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_large_white.png^[multiply:#fbdf00" },
			use_texture_alpha = "opaque",
			inventory_image = prefix5.."(signs_road_white.png^[multiply:#fbdf00)",
		},
	},
	brown_large_street_sign = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#fff",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large brown banner"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_large_white.png^[multiply:#754222" },
			use_texture_alpha = "opaque",
			inventory_image = prefix5.."(signs_road_white.png^[multiply:#754222)",
		},
	},
	invisible_large_street_sign_black_text = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#000",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large invisible banner with black text"),
			tiles = { "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_large_white.png^[opacity:0" },
			use_texture_alpha = "clip",
			inventory_image = prefix5.."(signs_road_white.png^[multiply:#999999)^(signs_road_letter.png^[multiply:#000000)^default_invisible_node_overlay.png",
		},
	},
	invisible_large_street_sign_white_text = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#fff",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large invisible banner with white text"),
			tiles = { "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_large_white.png^[opacity:0" },
			use_texture_alpha = "clip",
			inventory_image = prefix5.."(signs_road_white.png^[multiply:#999999)^signs_road_letter.png^default_invisible_node_overlay.png",
		},
	},
	invisible_large_street_sign_green_text = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#00ff00",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large invisible banner with green text"),
			tiles = { "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_large_white.png^[opacity:0" },
			use_texture_alpha = "clip",
			inventory_image = prefix5.."(signs_road_white.png^[multiply:#999999)^(signs_road_letter.png^[multiply:#00ff00)^default_invisible_node_overlay.png",
		},
	},
	invisible_large_street_sign_orange_text = {
		depth = 1/16,
		width = 64/16,
		height = 12/16,
		entity_fields = {
			maxlines = 1,
			color = "#ffbb00",
		},
		node_fields = {
		   visual_scale = 1,
			description = S("Large invisible banner with orange text"),
			tiles = { "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_large_white.png^[opacity:0" },
			use_texture_alpha = "clip",
			inventory_image = prefix5.."(signs_road_white.png^[multiply:#999999)^(signs_road_letter.png^[multiply:#ffbb00)^default_invisible_node_overlay.png",
		},
	},
	red_street_sign = {
		depth = 1/16,
		width = 1,
		height = 7/16,
		entity_fields = {
			size = { x = 1, y = 4/16 },
			maxlines = 1,
			color = "#000",
		},
		node_fields = {
			description = S("Red and white town sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_red_white.png" },
			use_texture_alpha = "opaque",
			inventory_image="signs_road_red_white.png",
		},
		allow_on_pole = true,
	},
	white_sign = {
		depth = 1/16,
		width = 1,
		height = 7/16,
		entity_fields = {
			size = { x = 1, y = 6/16 },
			maxlines = 2,
			color = "#000",
		},
		node_fields = {
			description = S("White road sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_white.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_white.png",
		},
		allow_on_pole = true,
	},
	white_end_sign = {
		depth = 1/16,
		width = 1,
		height = 7/16,
		entity_fields = {
			size = { x = 1, y = 6/16 },
			maxlines = 2,
			color = "#000",
		},
		node_fields = {
			description = S("White road end sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_white_end.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_white_end.png^[resize:32x32",
		},
		allow_on_pole = true,
	},
	black_sign = {
		depth = 1/16,
		width = 1,
		height = 7/16,
		entity_fields = {
			size = { x = 1, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Black road sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_white.png^[multiply:#000000" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_white.png^[multiply:#000000",
		},
		allow_on_pole = true,
	},
	brown_sign = {
		depth = 1/16,
		width = 1,
		height = 7/16,
		entity_fields = {
			size = { x = 1, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Brown road sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_white.png^[multiply:#754222" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_white.png^[multiply:#754222",
		},
		allow_on_pole = true,
	},
	blue_sign = {
		depth = 1/16,
		width = 1,
		height = 7/16,
		entity_fields = {
			size = { x = 1, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Blue road sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_blue.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_blue.png",
		},
		allow_on_pole = true,
	},
	green_sign = {
		depth = 1/16,
		width = 1,
		height = 7/16,
		entity_fields = {
			size = { x = 1, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Green road sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_green.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_green.png",
		},
		allow_on_pole = true,
	},
	yellow_sign = {
		depth = 1/16,
		width = 1,
		height = 7/16,
		entity_fields = {
			size = { x = 1, y = 6/16 },
			maxlines = 2,
			color = "#000",
		},
		node_fields = {
			description = S("Yellow road sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_yellow.png" },
			use_texture_alpha = "opaque",
			inventory_image="signs_road_yellow.png",
		},
		allow_on_pole = true,
	},
	red_sign = {
		depth = 1/16,
		width = 1,
		height = 7/16,
		entity_fields = {
			size = { x = 1, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Red road sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_red.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_red.png",
		},
		allow_on_pole = true,
	},
	inv_sign_black_text = {
		depth = 1/16,
		width = 1,
		height = 1,
		entity_fields = {
			size = { x = 3, y = 1 },
			maxlines = 4,
			color = "#000",
		},
		node_fields = {
			description = S("Invisible sign with black text"),
			tiles = { "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_white.png^[opacity:0" },
			use_texture_alpha = "clip",
			inventory_image = "signs_road_white.png^[multiply:#999999^(signs_road_letter.png^[multiply:#000000)^default_invisible_node_overlay.png",
		},
	},
	inv_sign_white_text = {
		depth = 1/16,
		width = 1,
		height = 1,
		entity_fields = {
			size = { x = 3, y = 1 },
			maxlines = 4,
			color = "#fff",
		},
		node_fields = {
			description = S("Invisible sign with white text"),
			tiles = { "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_white.png^[opacity:0" },
			use_texture_alpha = "clip",
			inventory_image = "signs_road_white.png^[multiply:#999999^signs_road_letter.png^default_invisible_node_overlay.png",
		},
	},
	inv_sign_orange_text = {
		depth = 1/16,
		width = 1,
		height = 1,
		entity_fields = {
			size = { x = 3, y = 1 },
			maxlines = 4,
			color = "#ffbb00",
		},
		node_fields = {
			description = S("Invisible sign with orange text"),
			tiles = { "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_white.png^[opacity:0" },
			use_texture_alpha = "clip",
			inventory_image = "signs_road_white.png^[multiply:#999999^(signs_road_letter.png^[multiply:#ffbb00)^default_invisible_node_overlay.png",
		},
	},
	inv_sign_green_text = {
		depth = 1/16,
		width = 1,
		height = 1,
		entity_fields = {
			size = { x = 3, y = 1 },
			maxlines = 4,
			color = "#00ff00",
		},
		node_fields = {
			description = S("Invisible sign with green text"),
			tiles = { "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_sides.png^[opacity:0",
			          "signs_road_sides.png^[opacity:0", "signs_road_white.png^[opacity:0" },
			use_texture_alpha = "clip",
			inventory_image = "signs_road_white.png^[multiply:#999999^(signs_road_letter.png^[multiply:#00ff00)^default_invisible_node_overlay.png",
		},
	},
	black_right_sign = {
		depth = 1/32,
		width = 1,
		height = 0.5,
		entity_fields = {
			aspect_ratio = 3/4,
			size = { x = 1, y = 3/16 },
			maxlines = 1,
			color = "#000",
		},
		node_fields = {
			description = S("Black direction sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_black_dir_right.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_black_dir_inventory.png",
			signs_other_dir = "signs_road:black_left_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
		},
		allow_on_pole = true,
	},
	black_left_sign = {
		depth = 1/32,
		width = 1,
		height = 0.5,
		entity_fields = {
			aspect_ratio = 3/4,
			size = { x = 1, y = 3/16 },
			maxlines = 1,
			color = "#000",
		},
		node_fields = {
			description = S("Black direction sign"),
			tiles = { "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_sides.png",
			          "signs_road_sides.png", "signs_road_black_dir_left.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_black_dir_inventory.png",
			signs_other_dir = "signs_road:black_right_sign",
			groups = { not_in_creative_inventory = 1 },
			drop = "signs_road:black_right_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
		},
		allow_on_pole = true,
	},
	white_right_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = -3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color = "#000",
		},
		node_fields = {
			description = S("White direction sign"),
			tiles = { "signs_road_white_direction.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_white_dir_inventory.png",
			signs_other_dir = "signs_road:white_left_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_right.obj",
			selection_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
		},
		allow_on_pole = true,
	},
	white_left_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = 3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color = "#000",
		},
		node_fields = {
			description = S("White direction sign"),
			tiles = { "signs_road_white_direction.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_white_dir_inventory.png^[transformFX",
			signs_other_dir = "signs_road:white_right_sign",
			on_place=signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_left.obj",
			selection_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			groups = { not_in_creative_inventory = 1 },
			drop = "signs_road:white_right_sign",
		},
		allow_on_pole = true,
	},
	brown_right_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = -3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Brown direction sign"),
			tiles = { "signs_road_white_direction.png^[multiply:#754222" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_white_dir_inventory.png^[multiply:#754222",
			signs_other_dir = "signs_road:brown_left_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_right.obj",
			selection_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
		},
		allow_on_pole = true,
	},
	brown_left_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = 3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Brown direction sign"),
			tiles = { "signs_road_white_direction.png^[multiply:#754222" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_white_dir_inventory.png^[multiply:#754222",
			signs_other_dir = "signs_road:brown_right_sign",
			on_place=signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_left.obj",
			selection_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			groups = { not_in_creative_inventory = 1 },
			drop = "signs_road:brown_right_sign",
		},
		allow_on_pole = true,
	},
	blue_right_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = -3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Blue direction sign"),
			tiles = { "signs_road_blue_direction.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_blue_dir_inventory.png",
			signs_other_dir = "signs_road:blue_left_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_right.obj",
			selection_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
		},
		allow_on_pole = true,
	},
	blue_left_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = 3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color="#fff",
		},
		node_fields = {
			description = S("Blue direction sign"),
			tiles = { "signs_road_blue_direction.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_blue_dir_inventory.png",
			signs_other_dir = "signs_road:blue_right_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_left.obj",
			selection_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			groups = { not_in_creative_inventory = 1 },
			drop = "signs_road:blue_right_sign",
		},
		allow_on_pole = true,
	},
	green_right_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = -3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Green direction sign"),
			use_texture_alpha = "opaque",
			tiles = { "signs_road_green_direction.png" },
			inventory_image = "signs_road_green_dir_inventory.png",
			signs_other_dir = "signs_road:green_left_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_right.obj",
			selection_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
		},
		allow_on_pole = true,
	},
	green_left_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = 3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color="#fff",
		},
		node_fields = {
			description = S("Green direction sign"),
			tiles = { "signs_road_green_direction.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_green_dir_inventory.png",
			signs_other_dir = "signs_road:green_right_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_left.obj",
			selection_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			groups = { not_in_creative_inventory = 1 },
			drop = "signs_road:green_right_sign",
		},
		allow_on_pole = true,
	},
	yellow_right_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = -3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color = "#000",
		},
		node_fields = {
			description = S("Yellow direction sign"),
			tiles = { "signs_road_yellow_direction.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_yellow_dir_inventory.png",
			signs_other_dir = "signs_road:yellow_left_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_right.obj",
			selection_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
		},
		allow_on_pole = true,
	},
	yellow_left_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = 3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color = "#000",
		},
		node_fields = {
			description = S("Yellow direction sign"),
			tiles = { "signs_road_yellow_direction.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_yellow_dir_inventory.png",
			signs_other_dir = "signs_road:yellow_right_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_left.obj",
			selection_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			groups = { not_in_creative_inventory = 1 },
			drop = "signs_road:yellow_right_sign",
		},
		allow_on_pole = true,
	},
	red_right_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = -3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Red direction sign"),
			tiles = { "signs_road_red_direction.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_red_dir_inventory.png",
			signs_other_dir = "signs_road:red_left_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_right.obj",
			selection_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -0.5, -7/32, 0.5, 7/16, 7/32, 7/16 } },
		},
		allow_on_pole = true,
	},
	red_left_sign = {
		depth = 1/16,
		width = 14/16,
		height = 7/16,
		entity_fields = {
			right = 3/32,
			size = { x = 12/16, y = 6/16 },
			maxlines = 2,
			color = "#fff",
		},
		node_fields = {
			description = S("Red direction sign"),
			tiles = { "signs_road_red_direction.png" },
			use_texture_alpha = "opaque",
			inventory_image = "signs_road_red_dir_inventory.png^[transformFX",
			signs_other_dir = "signs_road:red_right_sign",
			on_place = signs_api.on_place_direction,
			on_rightclick = signs_api.on_right_click_direction,
			drawtype = "mesh",
			mesh = "signs_dir_left.obj",
			selection_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			collision_box = { type = "fixed", fixed = { -7/16, -7/32, 0.5, 0.5, 7/32, 7/16 } },
			groups = { not_in_creative_inventory = 1 },
			drop = "signs_road:red_right_sign",
		},
		allow_on_pole = true,
	},
}

-- Node registration
signs_api.shape_selector_mode = "suppress"
for name, model in pairs(models)
do
	if name:match("_left_") or name:match("_right_") then
		signs_api.register_sign("signs_road", name, model)
	end
end
signs_api.shape_selector_mode = "with_dirsigns"
for name, model in pairs(models)
do
	if not (name:match("_left_") or name:match("_right_")) then
		signs_api.register_sign("signs_road", name, model)
	end
end
signs_api.shape_selector_mode = nil
