-- Definice materiálů, které bude možno vyhlazovat.
-- Každá položka bude doplněna o ["prefix"] a ["name"]
ch_smooth.materials = {
	{item = "default:desert_sand"},
	{item = "default:dirt"},
	{item = "default:dirt_with_coniferous_litter"},
	{item = "default:dirt_with_grass"},
	{item = "default:dirt_with_rainforest_litter"},
	-- {item = "default:dirt_with_snow"},
	-- {item = "default:dry_dirt_with_dry_grass"},
	{item = "default:gravel"},
	{item = "default:sand"},
	{item = "default:silver_sand"},
	{item = "default:snowblock"},
}

-- Definice tvarů
-- index => tabulka popisující obecný tvar
ch_smooth.general_shapes = {
	{
		type = "normal",
		prefix = "slab_",
		suffix = "",
		vxmzm = 0.5,
		vxpzm = 0.5,
		vxpzp = 0.5,
		vxmzp = 0.5,
	},
	{
		type = "normal",
		prefix = "slope_",
		suffix = "",
		vxmzm = 0,
		vxpzm = 0,
		vxpzp = 1,
		vxmzp = 1,
	},
	{
		type = "normal",
		prefix = "slope_",
		suffix = "_half",
		vxmzm = 0,
		vxpzm = 0,
		vxpzp = 0.5,
		vxmzp = 0.5,
	},
	{
		type = "normal",
		prefix = "slope_",
		suffix = "_half_raised",
		vxmzm = 0.5,
		vxpzm = 0.5,
		vxpzp = 1,
		vxmzp = 1,
	},
	{
		type = "normal",
		prefix = "slope_",
		suffix = "_inner",
		vxmzm = 1,
		vxpzm = 0,
		vxpzp = 1,
		vxmzp = 1,
	},
	{
		type = "normal",
		prefix = "slope_",
		suffix = "_inner_half",
		vxmzm = 0.5,
		vxpzm = 0,
		vxpzp = 0.5,
		vxmzp = 0.5,
	},
	{
		type = "normal",
		prefix = "slope_",
		suffix = "_outer",
		vxmzm = 0,
		vxpzm = 0,
		vxpzp = 0,
		vxmzp = 1,
	},
	{
		type = "normal",
		prefix = "slope_",
		-- suffix = "_outer_half",
		suffix = "_outer_cut_half",
		vxmzm = 0,
		vxpzm = 0,
		vxpzp = 0,
		vxmzp = 0.5,
	},
	{
		type = "normal",
		prefix = "slope_",
		suffix = "_outer_half_raised",
		vxmzm = 0.5,
		vxpzm = 0.5,
		vxpzp = 0.5,
		vxmzp = 1,
	},
	{
		type = "normal",
		prefix = "slope_",
		suffix = "_cut",
		vxmzm = 0.5,
		vxpzm = 0,
		vxpzp = 0.5,
		vxmzp = 1,
	},
	{
		type = "normal",
		prefix = "slope_",
		suffix = "_inner_cut_half_raised",
		vxmzm = 1,
		vxpzm = 0.5,
		vxpzp = 1,
		vxmzp = 1,
	},
	{
		type = "normal",
		prefix = "",
		suffix = "",
		vxmzm = 1,
		vxpzm = 1,
		vxpzp = 1,
		vxmzp = 1,
	},
	--[[ {
		type = "normal",
		prefix = "slope_",
		suffix = "_inner_half_raised",
		vxmzm = 1,
		vxpzm = 0.5,
		vxpzp = 1,
		vxmzp = 1,
	},
	]]
	-- DOUBLE SHAPES
	{
		type = "double",
		prefix = "slope_",
		suffix = "_inner_cut",
		upper_prefix = "slope_",
		upper_suffix = "_outer_cut",
		vxmzm = 1,
		vxpzm = 0,
		vxpzp = 1,
		vxmzp = 2,
	},
	{
		type = "double",
		prefix = "slope_",
		suffix = "_inner_cut_half_raised",
		upper_prefix = "slope_",
		upper_suffix = "_outer_cut_half",
		vxmzm = 1,
		vxpzm = 0.5,
		vxpzp = 1,
		vxmzp = 1.5,
	},
	{
		type = "bank",
		prefix = "bank_slope_",
		suffix = "",
		vxmzm = 1,
		vxpzm = 1,
		vxpzp = 2,
		vxmzp = 2,
	},
	{
		type = "bank",
		prefix = "bank_slope_",
		suffix = "_cut",
		vxmzm = 1.5,
		vxpzm = 1,
		vxpzp = 1.5,
		vxmzp = 2,
	},
	{
		type = "bank",
		prefix = "bank_slope_",
		suffix = "_half",
		vxmzm = 1,
		vxpzm = 1,
		vxpzp = 1.5,
		vxmzp = 1.5,
	},
	{
		type = "bank",
		prefix = "bank_slope_",
		suffix = "_outer_half_raised",
		vxmzm = 1.5,
		vxpzm = 1.5,
		vxpzp = 1.5,
		vxmzp = 2,
	},
	{
		type = "bank",
		prefix = "bank_slope_",
		suffix = "_outer_half",
		vxmzm = 1,
		vxpzm = 1,
		vxpzp = 1,
		vxmzp = 1.5,
	},
	{
		type = "bank",
		prefix = "bank_slope_",
		suffix = "_outer",
		vxmzm = 1,
		vxpzm = 1,
		vxpzp = 1,
		vxmzp = 2,
	},
	--[[
	{
		type = "bank",
		prefix = "bank_slope_",
		suffix = "_inner_half_raised",
		vxmzm = 2,
		vxpzm = 1.5,
		vxpzp = 2,
		vxmzp = 2,
	}, ]]
	--[[
	{
		type = "bank",
		prefix = "bank_slope_",
		suffix = "_inner_half",
		vxmzm = 1.5,
		vxpzm = 1,
		vxpzp = 1.5,
		vxmzp = 1.5,
	},
	]]
	{
		type = "double_bank",
		prefix = "bank_slope_",
		suffix = "_inner_cut_half_raised",
		upper_prefix = "slope_",
		upper_suffix = "_outer_cut_half",
		vxmzm = 2,
		vxpzm = 1.5,
		vxpzp = 2,
		vxmzp = 2.5,
	},
	{
		type = "bank",
		prefix = "bank_slope_",
		suffix = "_inner_cut_half",
		vxmzm = 1.5,
		vxpzm = 1,
		vxpzp = 1.5,
		vxmzp = 1.5,
	},
	{
		type = "double_bank",
		prefix = "bank_slope_",
		suffix = "_inner_cut",
		upper_prefix = "slope_",
		upper_suffix = "_outer_cut",
		vxmzm = 2,
		vxpzm = 1,
		vxpzp = 2,
		vxmzp = 3,
	},
	{
		type = "bank",
		prefix = "bank_slope_",
		suffix = "_inner",
		vxmzm = 2,
		vxpzm = 1,
		vxpzp = 2,
		vxmzp = 2,
	},
}
