local path = minetest.get_modpath("summer")
dofile(path.."/salvag.lua")
dofile(path.."/ombrellone.lua")
dofile(path.."/sdraia.lua")
dofile(path.."/porta.lua")
dofile(path.."/ombrellone_new.lua")
dofile(path.."/materassino.lua")
dofile(path.."/breccia.lua")
dofile(path.."/asciugamano.lua")
if minetest.get_modpath("3d_armor") then
dofile(path.."/occhiali.lua")
end
dofile(path.."/chest.lua")
dofile(path.."/portacenere.lua")
dofile(path.."/summerstair.lua")
dofile(path.."/barche.lua")
dofile(path.."/granite.lua")
dofile(path.."/canoa.lua")
dofile(path.."/craft.lua")
dofile(path.."/vetro.lua")
dofile(path.."/aliases.lua")
dofile(path.."/sabbia.lua")
dofile(path.."/mattone.lua")
dofile(path.."/pietra.lua")
dofile(path.."/pallone.lua")
dofile(path.."/granite.lua")
if minetest.get_modpath("cannabis") then
dofile(path.."/canapa.lua")
end
