print("[MOD BEGIN] " .. minetest.get_current_modname() .. "(" .. os.clock() .. ")")

local dofile = ch_core.compile_dofile()

-- dofile("dynamic_liquids.lua")
dofile("area_storages.lua")
-- dofile("areas_test.lua")
--dofile("clothinggen.lua")
-- dofile("colored_stone.lua")
-- dofile("chest.lua")
dofile("hud_test.lua")
-- dofile("extra_logging.lua")
dofile("interiors.lua")
dofile("landscape_generation.lua")
--dofile("path_generation.lua")
-- dofile("ui_page.lua")
dofile("globalstep_lag_logging.lua")
dofile("obj_in_radius_logging.lua")
-- dofile("markers.lua")
dofile("testcommand.lua")
dofile("testnodes.lua")
dofile("verify_tiles.lua")
-- dofile("wanted_blocks.lua")
----
-- dofile("array_stats.lua")

print("[MOD END] " .. minetest.get_current_modname() .. "(" .. os.clock() .. ")")
